project_id = "oddjqyvmkkzcagcyeofv"

[functions.create-notification]
verify_jwt = true

[functions.create-user]
verify_jwt = false

[functions.update-user-role]
verify_jwt = false

[functions.analyze-a3]
verify_jwt = true

[functions.a3-copilot]
verify_jwt = true

[functions.management-chat]
verify_jwt = false

[functions.ai-idea-assistant]
verify_jwt = false
